### ISSUE TITLE
todo fix

### ISSUE THREAD

**Issue by jackburkhardt** [dilanx/WedBars#16]
i dont feel like opening my ide again so im leaving this here. thought i fixed it but noooooooooo

```
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:?]
        at com.blockhead7360.mc.wedbars.arena.Arena.anotherGame(Arena.java:845) ~[?:?]
        at com.blockhead7360.mc.wedbars.arena.Arena$5.run(Arena.java:821) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by dilanx** [comment]
This is an issue with the next arena selection on game end (doesn't work when there's only one arena created) so I'll fix it lmao
